######################################################################
# Automatically generated by qmake (2.01a) Wed May 30 09:55:55 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ut.h
FORMS += ut.ui
SOURCES += epochtool.cpp ut.cpp
